<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\{Visite, Frais, Caution, Avance, Personne, Proprietaire, Appartement, Depense, TypeDepense, Contrat};
use App\Enums\ValidableEntityStatus;
use App\Events\ContratBailCreated;
use Illuminate\Support\Facades\DB;
use Carbon\Carbon;

class ContractSeeder extends Seeder
{
    public function run(): void
    {
        $data = [
            [
                'NOM_DU_LOCATAIRE' => 'MR KOUAKOU',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-03-08 00:00:00',
                'CODE_CLIENT' => '0708767047',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPOBGP6',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR DIAGOLA',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2020-01-30 00:00:00',
                'CODE_CLIENT' => '0505850775',
                'FRAIS_DAGENCE' => 65000.0,
                'CAUTION' => 130000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPU9J0N',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR TOTO',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2020-01-30 00:00:00',
                'CODE_CLIENT' => '0757873723',
                'FRAIS_DAGENCE' => 65000.0,
                'CAUTION' => 195000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP9CZLL',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR APPIA',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-02-20 00:00:00',
                'CODE_CLIENT' => '0102701822',
                'FRAIS_DAGENCE' => 70000.0,
                'CAUTION' => 210000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPFCHAS',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR COULIBALY',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-03-24 00:00:00',
                'CODE_CLIENT' => '0757462953',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPEMSVU',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOHE',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-04-11 00:00:00',
                'CODE_CLIENT' => '0788435282',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPAKNE0',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR BEMIAN',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-04-04 00:00:00',
                'CODE_CLIENT' => '0749633147',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPT1C09',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS AURELIE',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-07-31 00:00:00',
                'CODE_CLIENT' => '0707642279',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPKSGHD',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS ZAMBLE',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-08-01 00:00:00',
                'CODE_CLIENT' => '0777755265',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 135000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPAKXK',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KPATA',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-09-11 00:00:00',
                'CODE_CLIENT' => '0707309100',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 135000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPXHPXO',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS BOUO AFFOUA',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-02-01 00:00:00',
                'CODE_CLIENT' => '0708405954',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 240000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPWBUK1',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR MALAN BILE',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-11-01 00:00:00',
                'CODE_CLIENT' => '0554735728',
                'FRAIS_DAGENCE' => 90000.0,
                'CAUTION' => 180000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPHCMSZ',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOUAKOU LAZARE',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-04-23 00:00:00',
                'CODE_CLIENT' => '0757324178',
                'FRAIS_DAGENCE' => 90000.0,
                'CAUTION' => 180000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP8GN1Z',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR OUREGA BLY',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2021-02-01 00:00:00',
                'CODE_CLIENT' => '0758395077',
                'FRAIS_DAGENCE' => 85000.0,
                'CAUTION' => 255000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPPVK8Y',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS PIERRETTE',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2021-02-01 00:00:00',
                'CODE_CLIENT' => '0779253317',
                'FRAIS_DAGENCE' => '',
                'CAUTION' => '',
                'AVANCE' => '',
                'CODE_BIENS' => 'APPATE8T',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME KOUASSI SALOME',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-11-29 00:00:00',
                'CODE_CLIENT' => '0709210205',
                'FRAIS_DAGENCE' => 90000.0,
                'CAUTION' => 190000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPHHLJ5',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME OULAI CHANTALE',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 3',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-11-11 00:00:00',
                'CODE_CLIENT' => '0758354140',
                'FRAIS_DAGENCE' => 50000.0,
                'CAUTION' => 100000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPKK7U9',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR DIBY DIDIER',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 3',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-08-01 00:00:00',
                'CODE_CLIENT' => '0708205867',
                'FRAIS_DAGENCE' => 50000.0,
                'CAUTION' => 100000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP86ACL',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KONAN EZECHIEL',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 3',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-06-02 00:00:00',
                'CODE_CLIENT' => '0748866931',
                'FRAIS_DAGENCE' => 70000.0,
                'CAUTION' => 210000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP1QZAB',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME M\'BATTIEN',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 3',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-07-05 00:00:00',
                'CODE_CLIENT' => '0555385291',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP153M5',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR N\'GUESSAN',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 3',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2020-10-22 00:00:00',
                'CODE_CLIENT' => '0708397617',
                'FRAIS_DAGENCE' => 65000.0,
                'CAUTION' => 130000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPAODZT',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR YAO FERRAND',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 3',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2021-05-02 00:00:00',
                'CODE_CLIENT' => '0575202021',
                'FRAIS_DAGENCE' => 70000.0,
                'CAUTION' => 140000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPAUF32',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR DEYA BABA',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 3',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-03-25 00:00:00',
                'CODE_CLIENT' => '0747929646',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPX6EK7',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME GUIBADO JULIA',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA3',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-02-28 00:00:00',
                'CODE_CLIENT' => '0708684770',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPFG1JE',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS KONAN VICTOIRE',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA3',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-04-23 00:00:00',
                'CODE_CLIENT' => '',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPRBRMB',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR DOHOUN',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA6',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-10-20 00:00:00',
                'CODE_CLIENT' => '0747705289',
                'FRAIS_DAGENCE' => 250000.0,
                'CAUTION' => 500000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPUKTYJ',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR SOUMAHORO',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA6',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-10-28 00:00:00',
                'CODE_CLIENT' => '0759276993',
                'FRAIS_DAGENCE' => 250000.0,
                'CAUTION' => 500000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPLUBWB',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'UNIVERSAL HOTEL',
                'PROPRIETAIRES' => 'MR YAO',
                'NUMEROS' => '225 0707140102',
                'NOMS_DES_CITEES' => 'BERACA 6',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-09-06 00:00:00',
                'CODE_CLIENT' => '0759276993',
                'FRAIS_DAGENCE' => 250000.0,
                'CAUTION' => 500000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP7HH7M',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME BAYORO',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-04-02 00:00:00',
                'CODE_CLIENT' => '0747386880',
                'FRAIS_DAGENCE' => 200000.0,
                'CAUTION' => 600000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPK37SK',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME KODISSOU',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-03-07 00:00:00',
                'CODE_CLIENT' => '0701576593',
                'FRAIS_DAGENCE' => 200000.0,
                'CAUTION' => 400000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPYFSXO',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME KOUAME ADJOUA',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-04-01 00:00:00',
                'CODE_CLIENT' => '0707561415',
                'FRAIS_DAGENCE' => 200000.0,
                'CAUTION' => 600000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP27UFU',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME SAHUIE',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-11-21 00:00:00',
                'CODE_CLIENT' => '0707964867',
                'FRAIS_DAGENCE' => 85000.0,
                'CAUTION' => 255000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPDQFK4',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME AGUIE',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-11-21 00:00:00',
                'CODE_CLIENT' => '0747037501',
                'FRAIS_DAGENCE' => 85000.0,
                'CAUTION' => 255000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPMKTJH',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR ALLAO PAUL',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-08-19 00:00:00',
                'CODE_CLIENT' => '0707467636',
                'FRAIS_DAGENCE' => 85000.0,
                'CAUTION' => 255000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPMLFVP',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR AGBOSSE',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-08-05 00:00:00',
                'CODE_CLIENT' => '0171377624',
                'FRAIS_DAGENCE' => 85000.0,
                'CAUTION' => 255000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPISAHJ',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOUADIO KAN ERIC',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-11-18 00:00:00',
                'CODE_CLIENT' => '0758804707',
                'FRAIS_DAGENCE' => 85000.0,
                'CAUTION' => 255000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPGQQKW',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR GUINA STEPHANE',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-10-05 00:00:00',
                'CODE_CLIENT' => '0757962890',
                'FRAIS_DAGENCE' => 85000.0,
                'CAUTION' => 170000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP7WZVD',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR ALEBY',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-11-04 00:00:00',
                'CODE_CLIENT' => '0707267811',
                'FRAIS_DAGENCE' => 85000.0,
                'CAUTION' => 255000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP6KIMD',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME KARAMA',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA4',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-10-01 00:00:00',
                'CODE_CLIENT' => '0707763389',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPKLYBF',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME ALLA',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA5',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-04-01 00:00:00',
                'CODE_CLIENT' => '0709889466',
                'FRAIS_DAGENCE' => 200000.0,
                'CAUTION' => 400000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPIGDMP',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR COULIBALY',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA5',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-06-02 00:00:00',
                'CODE_CLIENT' => '0707521284',
                'FRAIS_DAGENCE' => 200000.0,
                'CAUTION' => '',
                'AVANCE' => '',
                'CODE_BIENS' => 'APPD61YE',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'SODEMI',
                'PROPRIETAIRES' => 'MR KANATE',
                'NUMEROS' => '',
                'NOMS_DES_CITEES' => 'BERACA7',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-02-23 00:00:00',
                'CODE_CLIENT' => '2722220101',
                'FRAIS_DAGENCE' => 700000.0,
                'CAUTION' => 1400000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPAFXPM',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'DR GNAPIA',
                'PROPRIETAIRES' => 'MR ASSE',
                'NUMEROS' => '225 0707974485',
                'NOMS_DES_CITEES' => 'BERACA8',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-06-05 00:00:00',
                'CODE_CLIENT' => '0798606017',
                'FRAIS_DAGENCE' => 400000.0,
                'CAUTION' => 800000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPADLN8',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS KONAN MORELLE',
                'PROPRIETAIRES' => 'MME N\'GUESSAN',
                'NUMEROS' => '225 0748645091',
                'NOMS_DES_CITEES' => 'KAMI',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-06-19 00:00:00',
                'CODE_CLIENT' => '0788441890',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPRW524',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME AKA',
                'PROPRIETAIRES' => 'MME N\'GUESSAN',
                'NUMEROS' => '225 0748645091',
                'NOMS_DES_CITEES' => 'KAMI',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-09-01 00:00:00',
                'CODE_CLIENT' => '0748211501',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP5RWC6',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS LOUA',
                'PROPRIETAIRES' => 'MME N\'GUESSAN',
                'NUMEROS' => '225 0748645091',
                'NOMS_DES_CITEES' => 'KAMI',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-11-04 00:00:00',
                'CODE_CLIENT' => '0749325242',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP06QOZ',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOUASSI MARC',
                'PROPRIETAIRES' => 'MME N\'GUESSAN',
                'NUMEROS' => '225 0748645091',
                'NOMS_DES_CITEES' => 'KAMI',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-12-05 00:00:00',
                'CODE_CLIENT' => '0707381190',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => '',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR LOGBO JEAN LUC',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2018-02-06 00:00:00',
                'CODE_CLIENT' => '0709605694',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 80000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPHCCSZ',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR ASSI KOUAME',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2017-09-28 00:00:00',
                'CODE_CLIENT' => '0707130152',
                'FRAIS_DAGENCE' => 40000.0,
                'CAUTION' => 80000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPUVCXG',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME N\'GUESSAN',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-06-10 00:00:00',
                'CODE_CLIENT' => '0555669448',
                'FRAIS_DAGENCE' => 50000.0,
                'CAUTION' => 100000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPH6HSK',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR GUIA VALERE',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-11-10 00:00:00',
                'CODE_CLIENT' => '0546141313',
                'FRAIS_DAGENCE' => '',
                'CAUTION' => '',
                'AVANCE' => '',
                'CODE_BIENS' => 'APP0O7Q',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS FANNY',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-04-01 00:00:00',
                'CODE_CLIENT' => '0798018259',
                'FRAIS_DAGENCE' => 50000.0,
                'CAUTION' => 100000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPGMTPH',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS AKOSSO BAZOU',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-08-01 00:00:00',
                'CODE_CLIENT' => '0709628650',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 135000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPCFWWP',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOUASSI N\'GBIN',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2021-05-19 00:00:00',
                'CODE_CLIENT' => '',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 90000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPPHCYR',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR ZOROBI MOCTAR',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-04-17 00:00:00',
                'CODE_CLIENT' => '0709628650',
                'FRAIS_DAGENCE' => 50000.0,
                'CAUTION' => 100000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPWRLUA',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOFFI ADAMMO',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2020-07-03 00:00:00',
                'CODE_CLIENT' => '0708006937',
                'FRAIS_DAGENCE' => 40000.0,
                'CAUTION' => 80000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP86UQT',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS KOUADIO RACHEL',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2020-04-30 00:00:00',
                'CODE_CLIENT' => '0767722088',
                'FRAIS_DAGENCE' => 40000.0,
                'CAUTION' => 80000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPSPFZY',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS KOUADIO AHOU',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-07-04 00:00:00',
                'CODE_CLIENT' => '0757790981',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 135000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPSQR7D',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR DIALLO DAVID',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2021-01-01 00:00:00',
                'CODE_CLIENT' => '0779837355',
                'FRAIS_DAGENCE' => 40000.0,
                'CAUTION' => 80000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPPCQ81',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KONAN KACOU',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-01-20 00:00:00',
                'CODE_CLIENT' => '0708913535',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 135000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPJR6YL',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS ATTOKPA ESTHER',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'EBENEZER',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-07-15 00:00:00',
                'CODE_CLIENT' => '0707696520',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 135000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPD94NQ',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS BARRO DJENEBOU',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2018-07-10 00:00:00',
                'CODE_CLIENT' => '0707496895',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 90000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPHGAZQ',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR ACHY SYLVAIN',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-11-01 00:00:00',
                'CODE_CLIENT' => '0777257293',
                'FRAIS_DAGENCE' => 50000.0,
                'CAUTION' => 100000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPVLAUT',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOUAKOU PEPIN',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2020-07-28 00:00:00',
                'CODE_CLIENT' => '0546783553',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 90000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPQ1SAS',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR BOUKOU',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-07-31 00:00:00',
                'CODE_CLIENT' => '0709689358',
                'FRAIS_DAGENCE' => 50000.0,
                'CAUTION' => 150000.0,
                'AVANCE' => 'Novembre',
                'CODE_BIENS' => 'APPCHUTP',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR ESSOH PAUL',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-08-07 00:00:00',
                'CODE_CLIENT' => '0759423414',
                'FRAIS_DAGENCE' => 50000.0,
                'CAUTION' => 100000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPJWREP',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOUASSI KOFFI',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-05-14 00:00:00',
                'CODE_CLIENT' => '0778027255',
                'FRAIS_DAGENCE' => '',
                'CAUTION' => '',
                'AVANCE' => '',
                'CODE_BIENS' => 'APPVUNP',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS ABOKAN SYNTICHE',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-10-26 00:00:00',
                'CODE_CLIENT' => '0747842543',
                'FRAIS_DAGENCE' => 50000.0,
                'CAUTION' => 100000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPFJQUY',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KONE PATRICE',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-05-10 00:00:00',
                'CODE_CLIENT' => '0173376260',
                'FRAIS_DAGENCE' => 45000.0,
                'CAUTION' => 90000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPHPDPF',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR YAO JULES',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-08-18 00:00:00',
                'CODE_CLIENT' => '0788820739',
                'FRAIS_DAGENCE' => 70000.0,
                'CAUTION' => 210000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPLUVBI',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR COULIBALY ELIE',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-11-05 00:00:00',
                'CODE_CLIENT' => '0707049406',
                'FRAIS_DAGENCE' => 70000.0,
                'CAUTION' => 210000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPZQEZT',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME KOUADIO',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-08-31 00:00:00',
                'CODE_CLIENT' => '0707908522',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPJ4NQ',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR SENIN STEPHANE',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-02-15 00:00:00',
                'CODE_CLIENT' => '0757342724',
                'FRAIS_DAGENCE' => 70000.0,
                'CAUTION' => 210000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPUTUF3',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR GBODJE',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2021-03-07 00:00:00',
                'CODE_CLIENT' => '0747776556',
                'FRAIS_DAGENCE' => 65000.0,
                'CAUTION' => 130000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPWY9TI',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR EGNI BERTRAND',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2019-11-22 00:00:00',
                'CODE_CLIENT' => '0708428176',
                'FRAIS_DAGENCE' => 65000.0,
                'CAUTION' => 130000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPZTKNA',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOFFI PATRICE',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2022-07-04 00:00:00',
                'CODE_CLIENT' => '0787872840',
                'FRAIS_DAGENCE' => 70000.0,
                'CAUTION' => 210000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPKJEN2',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'SANOGO ZIE',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN1',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-09-01 00:00:00',
                'CODE_CLIENT' => '0797052421',
                'FRAIS_DAGENCE' => 75000.0,
                'CAUTION' => 150000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPRVPVPP',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME N\'GATTA',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2021-05-05 00:00:00',
                'CODE_CLIENT' => '0758234449',
                'FRAIS_DAGENCE' => 70000.0,
                'CAUTION' => 140000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPJ9XY0',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MME BOLOU',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-07-01 00:00:00',
                'CODE_CLIENT' => '0777141231',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 240000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPPTNIW',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOFFI JACQUES',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-09-02 00:00:00',
                'CODE_CLIENT' => '0749336388',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPAIZ4R',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KOFFI JEAN-BAPTISTE',
                'PROPRIETAIRES' => 'MR SANOGO',
                'NUMEROS' => '225 0747142453',
                'NOMS_DES_CITEES' => 'NANAN2',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-06-01 00:00:00',
                'CODE_CLIENT' => '0757255570',
                'FRAIS_DAGENCE' => 110000.0,
                'CAUTION' => 220000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPR6PAY',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR KAMAGATE',
                'PROPRIETAIRES' => 'DR KOUAKOU',
                'NUMEROS' => '225 0708393363',
                'NOMS_DES_CITEES' => 'BANY',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-04-01 00:00:00',
                'CODE_CLIENT' => '0707260701',
                'FRAIS_DAGENCE' => 120000.0,
                'CAUTION' => 240000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPYBXZK',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR COULIBALY DIDIER',
                'PROPRIETAIRES' => 'DR KOUAKOU',
                'NUMEROS' => '225 0708393363',
                'NOMS_DES_CITEES' => 'BANY',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2021-08-30 00:00:00',
                'CODE_CLIENT' => '0747764498',
                'FRAIS_DAGENCE' => 120000.0,
                'CAUTION' => 300000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPJJPLG',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR ADINCI',
                'PROPRIETAIRES' => 'DR KOUAKOU',
                'NUMEROS' => '225 0708393363',
                'NOMS_DES_CITEES' => 'BANY',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-08-25 00:00:00',
                'CODE_CLIENT' => '0709522359',
                'FRAIS_DAGENCE' => 120000.0,
                'CAUTION' => 360000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APP4TXYM',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR DEST LATRILLE',
                'PROPRIETAIRES' => 'MR KOUAKOU',
                'NUMEROS' => '225 0707827172',
                'NOMS_DES_CITEES' => 'NOUVELLE CITEE',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-09-16 00:00:00',
                'CODE_CLIENT' => '',
                'FRAIS_DAGENCE' => 80000.0,
                'CAUTION' => 160000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPUKZTB',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR DEST LATRILLE',
                'PROPRIETAIRES' => 'MR KOUAKOU',
                'NUMEROS' => '225 0707827172',
                'NOMS_DES_CITEES' => 'NOUVELLE CITEE',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-09-01 00:00:00',
                'CODE_CLIENT' => '0748229325',
                'FRAIS_DAGENCE' => 170000.0,
                'CAUTION' => 340000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPEGANZ',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MISS SARAH',
                'PROPRIETAIRES' => 'MR KOUAKOU',
                'NUMEROS' => '225 0707827172',
                'NOMS_DES_CITEES' => 'NOUVELLE CITEE',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-09-01 00:00:00',
                'CODE_CLIENT' => '0779733527',
                'FRAIS_DAGENCE' => 170000.0,
                'CAUTION' => 340000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPN1PZ2',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR DEST LATRILLE',
                'PROPRIETAIRES' => 'MR KOUAKOU',
                'NUMEROS' => '225 0707827172',
                'NOMS_DES_CITEES' => 'NOUVELLE CITEE',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-09-06 00:00:00',
                'CODE_CLIENT' => '',
                'FRAIS_DAGENCE' => 170000.0,
                'CAUTION' => 340000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPHV3M0',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR AMAKI TANOH',
                'PROPRIETAIRES' => 'MR KOUAKOU',
                'NUMEROS' => '225 0707827172',
                'NOMS_DES_CITEES' => 'NOUVELLE CITEE',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-06-21 00:00:00',
                'CODE_CLIENT' => '0747993825',
                'FRAIS_DAGENCE' => 110000.0,
                'CAUTION' => 220000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPIZUFR',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR DEST LATRILLE',
                'PROPRIETAIRES' => 'MR KOUAKOU',
                'NUMEROS' => '225 0707827172',
                'NOMS_DES_CITEES' => 'NOUVELLE CITEE',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2025-05-15 00:00:00',
                'CODE_CLIENT' => '',
                'FRAIS_DAGENCE' => 110000.0,
                'CAUTION' => 220000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPZQCKU',
                'POURCENTAGE_PROPRIETAIRE' => 0.92,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR WANG YUKAI',
                'PROPRIETAIRES' => 'MR BONY',
                'NUMEROS' => '225 0768922384',
                'NOMS_DES_CITEES' => 'MILLIONNAIRE',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2016-12-05 00:00:00',
                'CODE_CLIENT' => '0789669966',
                'FRAIS_DAGENCE' => 500000.0,
                'CAUTION' => 1200000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPDY8Q2',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR WANG YUKAI',
                'PROPRIETAIRES' => 'MR BONY',
                'NUMEROS' => '225 0768922384',
                'NOMS_DES_CITEES' => 'MILLIONNAIRE',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2023-09-05 00:00:00',
                'CODE_CLIENT' => '0789669966',
                'FRAIS_DAGENCE' => 250000.0,
                'CAUTION' => 0.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPIWLUN',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
            [
                'NOM_DU_LOCATAIRE' => 'MR LIU XIEMEN',
                'PROPRIETAIRES' => 'MR BONY',
                'NUMEROS' => '225 0768922384',
                'NOMS_DES_CITEES' => 'MILLIONNAIRE',
                'MONTANT_DE_LA_VISITE' => 2000,
                'DATE_VISITE' => '2024-07-04 00:00:00',
                'CODE_CLIENT' => '0757206521',
                'FRAIS_DAGENCE' => 500000.0,
                'CAUTION' => 1000000.0,
                'AVANCE' => '',
                'CODE_BIENS' => 'APPVUZ2Z',
                'POURCENTAGE_PROPRIETAIRE' => 0.9,
            ],
        ];

        // Créer ou récupérer le TypeDepense "Dépense d'ajustement"
        $typeDepenseAjustement = TypeDepense::firstOrCreate(['nom' => 'Dépense d\'ajustement']);

        $this->command->info("✓ TypeDepense 'Dépense d'ajustement' prêt (ID: {$typeDepenseAjustement->id})");

        // Traitement des données pour créer les contrats
        $successCount = 0;
        $errorCount = 0;
        $ajustementCount = 0;
        $totalLines = count($data);

        $this->command->info("Démarrage du traitement de {$totalLines} lignes...");
        $this->command->newLine();

        foreach ($data as $index => $row) {
            DB::transaction(function () use ($row, $index, &$successCount, &$errorCount, &$ajustementCount, $typeDepenseAjustement) {
                try {
                    // 1. Trouver les entités
                    // Ajouter le préfixe +225 pour les téléphones
                    $telephoneClient = !empty($row['CODE_CLIENT']) ? '+225 ' . $row['CODE_CLIENT'] : '';
                    $telephoneProprio = '+' . $row['NUMEROS'];

                    $personne = Personne::where('telephone', $telephoneClient)->first();
                    // Recherche du propriétaire uniquement par téléphone
                    $proprietaire = Proprietaire::where('telephone', $telephoneProprio)->first();
                    $appartement = Appartement::where('reference', $row['CODE_BIENS'])->first();

                    // Validation
                    if (!$personne) {
                        $this->command->error("✗ Ligne {$index}: Personne non trouvée - Tel: {$row['CODE_CLIENT']}, Nom: {$row['NOM_DU_LOCATAIRE']}");
                        $errorCount++;
                        return;
                    }

                    if (!$proprietaire) {
                        $this->command->error("✗ Ligne {$index}: Propriétaire non trouvé - Nom: {$row['PROPRIETAIRES']}, Tel: {$row['NUMEROS']}");
                        $errorCount++;
                        return;
                    }

                    if (!$appartement) {
                        $this->command->error("✗ Ligne {$index}: Appartement non trouvé - Code: {$row['CODE_BIENS']}");
                        $errorCount++;
                        return;
                    }

                    // Vérifier si un contrat en cours existe déjà pour cette personne et cet appartement
                    $contratExistant = Contrat::whereHasMorph('operation', [Visite::class], function ($query) use ($personne, $appartement) {
                        $query->where('personne_id', $personne->id)
                            ->where('appartement_id', $appartement->id);
                    })->where('etat', 'en cours')->exists();

                    if ($contratExistant) {
                        $this->command->warn("⚠ Ligne {$index}: Contrat en cours déjà existant - Client: {$personne->nom_complet}, Bien: {$appartement->reference} (ignoré)");
                        $errorCount++;
                        return;
                    }

                    // 2. Calculs
                    $fraisExact = $row['FRAIS_DAGENCE'] / $appartement->montant_location;
                    $cautionExact = $row['CAUTION'] / $appartement->montant_location;

                    // Arrondir vers le haut (ceil) pour les mois
                    $moisFrais = (int)ceil($fraisExact);
                    $moisCaution = (int)ceil($cautionExact);

                    // Calculer les ajustements (différence entre le montant réel et le montant arrondi)
                    $montantFraisCalcule = $moisFrais * $appartement->montant_location;
                    $montantCautionCalcule = $moisCaution * $appartement->montant_location;

                    $ajustementFrais = $montantFraisCalcule - $row['FRAIS_DAGENCE'];
                    $ajustementCaution = $montantCautionCalcule - $row['CAUTION'];
                    $montantAjustementTotal = (int)($ajustementFrais + $ajustementCaution);

                    $commission = (int)($row['POURCENTAGE_PROPRIETAIRE'] * 100);
                    $fraisDossier = (int)($appartement->montant_location * 0.10); // 10% du montant de location

                    // 3. Créer la visite
                    $visite = Visite::create([
                        'personne_id' => $personne->id,
                        'appartement_id' => $appartement->id,
                        'montant' => $row['MONTANT_DE_LA_VISITE'],
                        'frais_dossier' => $fraisDossier,
                        'status' => ValidableEntityStatus::WAIT->value,
                    ]);
                    $visite->genererCode();
                    $visite->setExpiration();
                    $visite->save();

                    // 4. Créer Frais, Caution, Avance
                    Frais::create(['visite_id' => $visite->id, 'mois' => $moisFrais]);
                    Caution::create(['visite_id' => $visite->id, 'mois' => $moisCaution]);
                    Avance::create(['visite_id' => $visite->id, 'mois' => 0]);

                    // 5. Créer le contrat directement
                    $contrat = Contrat::create([
                        'debut' => Carbon::parse($row['DATE_VISITE'])->format('Y-m-d'),
                        'commission' => $commission,
                        'montant_location' => $appartement->montant_location,
                    ]);

                    $contrat->operation()->associate($visite)->save();
                    $visite->setValide();
                    $appartement->setBusy();

                    // Déclencher l'événement pour créer la dette
                    ContratBailCreated::dispatch($contrat, $visite);

                    // 6. Créer la dépense d'ajustement si nécessaire
                    if ($montantAjustementTotal > 0) {
                        $depense = Depense::create([
                            'titre' => 'Ajustement caution/frais - ' . $visite->code,
                            'montant' => $montantAjustementTotal,
                            'description' => sprintf(
                                'Ajustement pour la visite %s (Client: %s, Bien: %s). Frais: %.2f mois, Caution: %.2f mois',
                                $visite->code,
                                $personne->nom_complet,
                                $appartement->reference,
                                $fraisExact,
                                $cautionExact
                            ),
                            'type_depense_id' => $typeDepenseAjustement->id,
                        ]);
                        $depense->setValide();

                        $this->command->warn("  ↳ Dépense d'ajustement: " . number_format($montantAjustementTotal, 0, ',', ' ') . " FCFA (Frais: " . number_format((int)$ajustementFrais, 0, ',', ' ') . " + Caution: " . number_format((int)$ajustementCaution, 0, ',', ' ') . ")");

                        $ajustementCount++;
                    }

                    $this->command->info("✓ Ligne {$index}: Contrat {$visite->code} créé - Client: {$personne->nom_complet} - Bien: {$appartement->reference}");

                    $successCount++;
                } catch (\Exception $e) {
                    $this->command->error("✗ Ligne {$index}: Erreur - " . $e->getMessage());
                    $errorCount++;
                }
            });
        }

        // Afficher le résumé
        $this->command->newLine();
        $this->command->info("═══════════════════════════════════════════════════════════");
        $this->command->info("                    RÉSUMÉ DU TRAITEMENT                    ");
        $this->command->info("═══════════════════════════════════════════════════════════");
        $this->command->info("✓ Contrats créés avec succès    : {$successCount}");
        $this->command->warn("⚠ Dépenses d'ajustement créées  : {$ajustementCount}");
        $this->command->error("✗ Erreurs rencontrées           : {$errorCount}");
        $this->command->info("═══════════════════════════════════════════════════════════");
    }
}
